services:
  postgres:
    image: postgres:15
    container_name: postgres_prisma_app
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"  # <--- changed here
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  